# Generated by Django 6.0.1 on 2026-06-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_low_stock_threshold'),
        ('vendors', '0007_vendorsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1000, help_text='Maximum items warehouse can hold')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='vendors.branch')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'branch', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Specific warehouse within the branch (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'branch', 'warehouse')},
        ),
    ]
