# Generated by Django 6.0.5 on 2026-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
