# Generated by Django 6.0.5 on 2026-05-18 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0003_vendorstaff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("inventory", "Inventory Staff"),
                    ("dispatcher", "Dispatcher"),
                    ("rider", "Rider"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendorstaff",
            unique_together={("vendor", "user")},
        ),
    ]
