# Generated by Django 6.0.5 on 2026-05-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstaff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='vendors.branch'),
        ),
    ]
